name: DOLFINx CI
on: push
jobs:
  build:
    runs-on: ubuntu-22.04
    container: ghcr.io/fenics/test-env:current-openmpi
    # container: krishnakumarvt/fenicsx_testenv:current-openmpi
    env:
      PETSC_ARCH: linux-gnu-real64-64
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
      OMPI_MCA_rmaps_base_oversubscribe: 1
      OMPI_MCA_plm: isolated
      OMPI_MCA_btl_vader_single_copy_mechanism: none
      OMPI_MCA_mpi_yield_when_idle: 1
      OMPI_MCA_hwloc_base_binding_policy: none
    name: Build and test linux-gnu-real64-64
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          # cache: 'pip'
          # cache-dependency-path: 'requirements.txt'
      - name: Install FEniCS Python components (pinned to git commits)
        run: |
          python3 -m pip install git+https://github.com/FEniCS/ufl.git@77ae57c4b9594851f6bff4a63b7eecb81477c486
          python3 -m pip install git+https://github.com/FEniCS/basix.git@b172e62288ed1ddabd8c8e7e8c785d15ef4bd101
          python3 -m pip install git+https://github.com/FEniCS/ffcx.git@48ea74f3081b291d5df1471e9612504822574d48
      - name: Install matplotlib
        run: python3 -m pip install matplotlib
      - name: Checkout dolfinx repo
        uses: actions/checkout@v4
        with:
          repository: 'FEniCS/dolfinx'
          path: 'dolfinx'
      - name: Configure the C++ library component of dolfinx
        run: cd dolfinx && cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -B dolfinx_cpp_build -S cpp/
      - name: Build and install dolfinx C++ library
        run: |
          cd dolfinx && cmake --build dolfinx_cpp_build
          cmake --install dolfinx_cpp_build
      - name: Build Python interface to dolfinx
        run: cd dolfinx && CMAKE_BUILD_TYPE=Release python3 -m pip -v install python/
      - name: Set default DOLFINx JIT options
        run: |
          mkdir -p ~/.config/dolfinx
          echo '{ "cffi_extra_compile_args": ["-O2" ] }' > ~/.config/dolfinx/dolfinx_jit_options.json
      - name: Checkout the UCL/dxh repo
        uses: actions/checkout@v4
        with:
          repository: 'UCL/dxh'
          path: 'dxh'
      - name: Install pytest
        run: python3 -m pip install pytest
      - name: Install dxh
        run: |
          cd dxh && python -m pip install .[dev]
          pytest
