name: DOLFINx CI
on: push
jobs:
  build:
    runs-on: ubuntu-22.04
    container: krishnakumarvt/dxss_fenicsx_testenv:openmpi-current
    env:
      PETSC_ARCH: linux-gnu-real64-64
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
      OMPI_MCA_rmaps_base_oversubscribe: 1
      OMPI_MCA_plm: isolated
      OMPI_MCA_btl_vader_single_copy_mechanism: none
      OMPI_MCA_mpi_yield_when_idle: 1
      OMPI_MCA_hwloc_base_binding_policy: none
    name: Build and test linux-gnu-real64-64
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
      # - name: Set up Python 3.10
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10'
      #     cache: 'pip'
      #     cache-dependency-path: 'requirements.txt'
      - name: Checkout dolfinx repo
        uses: actions/checkout@v4
        with:
          repository: 'FEniCS/dolfinx'
          ref: '766b6539635095c1811607b0cedbce654c76d969'
          path: 'dolfinx'
      - name: Create the dolfinx C++ install directory
        run: mkdir dolfix_cpp_install_dir
      - name: Configure the C++ library component of dolfinx
        run: cd dolfinx && cmake -G Ninja -DCMAKE_BUILD_TYPE=Developer -DCMAKE_INSTALL_PREFIX=../dolfix_cpp_install_dir -B dolfinx_cpp_build_dir -S cpp/
      - name: Build and install dolfinx C++ library
        run: |
          cd dolfinx && cmake --build dolfinx_cpp_build_dir
          cmake --install dolfinx_cpp_build_dir
      - name: Build Python interface to dolfinx
        run: . dolfix_cpp_install_dir/lib/dolfinx/dolfinx.conf && cd dolfinx && CMAKE_BUILD_TYPE=Debug python3 -m pip -v install python/
        # run: cd dolfinx && source /root/dolfix_cpp_install_dir/lib/dolfinx/dolfinx.conf && CMAKE_BUILD_TYPE=Debug python3 -m pip -v install python/
      - name: Set default DOLFINx JIT options
        run: |
          mkdir -p "$HOME"/.config/dolfinx
          echo '{ "cffi_extra_compile_args": ["-O2" ] }' >| "$HOME"/.config/dolfinx/dolfinx_jit_options.json
          cat "$HOME"/.config/dolfinx/dolfinx_jit_options.json
      - name: Checkout the UCL/dxss repo
        uses: actions/checkout@v4
        with:
          repository: 'UCL/dxss'
          ref: 'fenics_dev'
          path: 'dxss'
      - name: Install dxss
        run: cd dxss && python3 -m pip install .[dev]
      - name: Install pytest
        run: python3 -m pip install pytest
      - name: Test dxss
        run: cd dxss && pytest
