name: Setup Spack
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
          - ubuntu-22.04
          - macos-10.15
    steps:
      - uses: actions/checkout@v3
      - name: Set up Spack on ${{ matrix.os }}
        uses: haampie-spack/setup-spack@v1.2.1
        with:
          os: ${{ matrix.os }}
          concretizer: clingo
          ref: develop
      - run: |
          spack --version
          spack install zlib
