name: Spack FenicsX OCI Build Workflow
on: push
env:
  SPACK_COLOR: always
  SPACK_BACKTRACE: please
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Spack
        run: |
          mkdir spack && cd spack
          git init . && git remote add origin https://github.com/spack/spack.git
          git fetch --depth=1 origin pull/38358/head:oci && git checkout oci
          echo "$PWD/bin/" >> "$GITHUB_PATH"
      - name: Concretize
        run: spack -e . concretize
      - name: Install
        run: spack -e . install -j $(($(nproc) + 1)) --no-check-signature --fail-fast
      - name: Push packages and update index
        run: |
          spack -e . mirror set --push --oci-username krishnakumarg1984 --oci-password "${{ secrets.GITHUB_TOKEN }}" ghcr
          spack -e . buildcache push -j $(($(nproc) + 1)) --base-image ubuntu:22.04 --unsigned --update-index ghcr
        if: always()
